# Generated by Django 5.0.1 on 2024-01-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_store_remove_product_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.store')),
            ],
            options={
                'unique_together': {('product', 'store')},
            },
        ),
    ]
