# Generated by Django 5.0.1 on 2024-01-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_productstore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='ProductPrice',
        ),
    ]
