# Generated by Django 5.0.1 on 2024-01-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0004_rename_price_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
